apiVersion: v1
kind: ConfigMap
metadata:
  name: f5-as3-declaration
  namespace: blue
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "label": "http",
            "remark": "blue namespace",
            "bluetenant": {
                "class": "Tenant",
                "blueapp": {
                    "class": "Application",
                    "template": "generic",
                    "blueapp": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.1.10.12"
                        ],
                        "pool": "bluepool",
                        "virtualPort": 80
                    },
                    "bluepool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
