apiVersion: v1
kind: ConfigMap
metadata:
  name: f5-as3-declaration
  namespace: red
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "label": "http",
            "remark": "red namespace",
            "redtenant": {
                "class": "Tenant",
                "redapp": {
                    "class": "Application",
                    "template": "generic",
                    "redapp": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.1.10.11"
                        ],
                        "pool": "redpool",
                        "virtualPort": 80
                    },
                    "redpool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
